name: Audit

on:
  push:
    paths:
      - '**/Cargo.toml'
  schedule:
    - cron: '0 2 * * 1'

jobs:
  audit:
    name: audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
